name: core_module
description: A new flutter plugin project.
version: 0.0.1
author: null
homepage: null

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tech.robsonsilva.core_module
        pluginClass: CoreModulePlugin
      ios:
        pluginClass: CoreModulePlugin
