name: home_module
description: Home module.
version: 0.0.1
author: null
homepage: null

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  core_module:
    path: ../core_module
  flutter_modular: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tech.robsonsilva.home_module
        pluginClass: HomeModulePlugin
      ios:
        pluginClass: HomeModulePlugin
