const gitHubResult = '''
{
  "total_count": 3171,
  "incomplete_results": false,
  "items": [
    {
      "login": "Robson",
      "id": 24928,
      "node_id": "MDQ6VXNlcjI0OTI4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/24928?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Robson",
      "html_url": "https://github.com/Robson",
      "followers_url": "https://api.github.com/users/Robson/followers",
      "following_url": "https://api.github.com/users/Robson/following{/other_user}",
      "gists_url": "https://api.github.com/users/Robson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Robson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Robson/subscriptions",
      "organizations_url": "https://api.github.com/users/Robson/orgs",
      "repos_url": "https://api.github.com/users/Robson/repos",
      "events_url": "https://api.github.com/users/Robson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Robson/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonvleite",
      "id": 8345682,
      "node_id": "MDQ6VXNlcjgzNDU2ODI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8345682?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonvleite",
      "html_url": "https://github.com/robsonvleite",
      "followers_url": "https://api.github.com/users/robsonvleite/followers",
      "following_url": "https://api.github.com/users/robsonvleite/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonvleite/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonvleite/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonvleite/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonvleite/orgs",
      "repos_url": "https://api.github.com/users/robsonvleite/repos",
      "events_url": "https://api.github.com/users/robsonvleite/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonvleite/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonmarques",
      "id": 861751,
      "node_id": "MDQ6VXNlcjg2MTc1MQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/861751?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonmarques",
      "html_url": "https://github.com/robsonmarques",
      "followers_url": "https://api.github.com/users/robsonmarques/followers",
      "following_url": "https://api.github.com/users/robsonmarques/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonmarques/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonmarques/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonmarques/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonmarques/orgs",
      "repos_url": "https://api.github.com/users/robsonmarques/repos",
      "events_url": "https://api.github.com/users/robsonmarques/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonmarques/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonsilv4",
      "id": 17673296,
      "node_id": "MDQ6VXNlcjE3NjczMjk2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/17673296?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonsilv4",
      "html_url": "https://github.com/robsonsilv4",
      "followers_url": "https://api.github.com/users/robsonsilv4/followers",
      "following_url": "https://api.github.com/users/robsonsilv4/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonsilv4/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonsilv4/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonsilv4/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonsilv4/orgs",
      "repos_url": "https://api.github.com/users/robsonsilv4/repos",
      "events_url": "https://api.github.com/users/robsonsilv4/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonsilv4/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonpeixoto",
      "id": 124390,
      "node_id": "MDQ6VXNlcjEyNDM5MA==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/124390?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonpeixoto",
      "html_url": "https://github.com/robsonpeixoto",
      "followers_url": "https://api.github.com/users/robsonpeixoto/followers",
      "following_url": "https://api.github.com/users/robsonpeixoto/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonpeixoto/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonpeixoto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonpeixoto/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonpeixoto/orgs",
      "repos_url": "https://api.github.com/users/robsonpeixoto/repos",
      "events_url": "https://api.github.com/users/robsonpeixoto/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonpeixoto/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonbittencourt",
      "id": 1248602,
      "node_id": "MDQ6VXNlcjEyNDg2MDI=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1248602?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonbittencourt",
      "html_url": "https://github.com/robsonbittencourt",
      "followers_url": "https://api.github.com/users/robsonbittencourt/followers",
      "following_url": "https://api.github.com/users/robsonbittencourt/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonbittencourt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonbittencourt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonbittencourt/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonbittencourt/orgs",
      "repos_url": "https://api.github.com/users/robsonbittencourt/repos",
      "events_url": "https://api.github.com/users/robsonbittencourt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonbittencourt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RobsonGap",
      "id": 22720178,
      "node_id": "MDQ6VXNlcjIyNzIwMTc4",
      "avatar_url": "https://avatars0.githubusercontent.com/u/22720178?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RobsonGap",
      "html_url": "https://github.com/RobsonGap",
      "followers_url": "https://api.github.com/users/RobsonGap/followers",
      "following_url": "https://api.github.com/users/RobsonGap/following{/other_user}",
      "gists_url": "https://api.github.com/users/RobsonGap/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RobsonGap/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RobsonGap/subscriptions",
      "organizations_url": "https://api.github.com/users/RobsonGap/orgs",
      "repos_url": "https://api.github.com/users/RobsonGap/repos",
      "events_url": "https://api.github.com/users/RobsonGap/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RobsonGap/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonalvz",
      "id": 25908395,
      "node_id": "MDQ6VXNlcjI1OTA4Mzk1",
      "avatar_url": "https://avatars3.githubusercontent.com/u/25908395?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonalvz",
      "html_url": "https://github.com/robsonalvz",
      "followers_url": "https://api.github.com/users/robsonalvz/followers",
      "following_url": "https://api.github.com/users/robsonalvz/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonalvz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonalvz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonalvz/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonalvz/orgs",
      "repos_url": "https://api.github.com/users/robsonalvz/repos",
      "events_url": "https://api.github.com/users/robsonalvz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonalvz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "bethrobson",
      "id": 30760,
      "node_id": "MDQ6VXNlcjMwNzYw",
      "avatar_url": "https://avatars0.githubusercontent.com/u/30760?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bethrobson",
      "html_url": "https://github.com/bethrobson",
      "followers_url": "https://api.github.com/users/bethrobson/followers",
      "following_url": "https://api.github.com/users/bethrobson/following{/other_user}",
      "gists_url": "https://api.github.com/users/bethrobson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bethrobson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bethrobson/subscriptions",
      "organizations_url": "https://api.github.com/users/bethrobson/orgs",
      "repos_url": "https://api.github.com/users/bethrobson/repos",
      "events_url": "https://api.github.com/users/bethrobson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bethrobson/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonribeiroft",
      "id": 13341506,
      "node_id": "MDQ6VXNlcjEzMzQxNTA2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/13341506?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonribeiroft",
      "html_url": "https://github.com/robsonribeiroft",
      "followers_url": "https://api.github.com/users/robsonribeiroft/followers",
      "following_url": "https://api.github.com/users/robsonribeiroft/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonribeiroft/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonribeiroft/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonribeiroft/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonribeiroft/orgs",
      "repos_url": "https://api.github.com/users/robsonribeiroft/repos",
      "events_url": "https://api.github.com/users/robsonribeiroft/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonribeiroft/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsoncouto",
      "id": 18122592,
      "node_id": "MDQ6VXNlcjE4MTIyNTky",
      "avatar_url": "https://avatars0.githubusercontent.com/u/18122592?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsoncouto",
      "html_url": "https://github.com/robsoncouto",
      "followers_url": "https://api.github.com/users/robsoncouto/followers",
      "following_url": "https://api.github.com/users/robsoncouto/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsoncouto/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsoncouto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsoncouto/subscriptions",
      "organizations_url": "https://api.github.com/users/robsoncouto/orgs",
      "repos_url": "https://api.github.com/users/robsoncouto/repos",
      "events_url": "https://api.github.com/users/robsoncouto/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsoncouto/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonmobile",
      "id": 9312175,
      "node_id": "MDQ6VXNlcjkzMTIxNzU=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/9312175?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonmobile",
      "html_url": "https://github.com/robsonmobile",
      "followers_url": "https://api.github.com/users/robsonmobile/followers",
      "following_url": "https://api.github.com/users/robsonmobile/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonmobile/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonmobile/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonmobile/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonmobile/orgs",
      "repos_url": "https://api.github.com/users/robsonmobile/repos",
      "events_url": "https://api.github.com/users/robsonmobile/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonmobile/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "camanducci",
      "id": 4296689,
      "node_id": "MDQ6VXNlcjQyOTY2ODk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4296689?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/camanducci",
      "html_url": "https://github.com/camanducci",
      "followers_url": "https://api.github.com/users/camanducci/followers",
      "following_url": "https://api.github.com/users/camanducci/following{/other_user}",
      "gists_url": "https://api.github.com/users/camanducci/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/camanducci/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/camanducci/subscriptions",
      "organizations_url": "https://api.github.com/users/camanducci/orgs",
      "repos_url": "https://api.github.com/users/camanducci/repos",
      "events_url": "https://api.github.com/users/camanducci/events{/privacy}",
      "received_events_url": "https://api.github.com/users/camanducci/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsontenorio",
      "id": 118955,
      "node_id": "MDQ6VXNlcjExODk1NQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118955?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsontenorio",
      "html_url": "https://github.com/robsontenorio",
      "followers_url": "https://api.github.com/users/robsontenorio/followers",
      "following_url": "https://api.github.com/users/robsontenorio/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsontenorio/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsontenorio/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsontenorio/subscriptions",
      "organizations_url": "https://api.github.com/users/robsontenorio/orgs",
      "repos_url": "https://api.github.com/users/robsontenorio/repos",
      "events_url": "https://api.github.com/users/robsontenorio/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsontenorio/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonamendonca",
      "id": 18629707,
      "node_id": "MDQ6VXNlcjE4NjI5NzA3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/18629707?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonamendonca",
      "html_url": "https://github.com/robsonamendonca",
      "followers_url": "https://api.github.com/users/robsonamendonca/followers",
      "following_url": "https://api.github.com/users/robsonamendonca/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonamendonca/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonamendonca/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonamendonca/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonamendonca/orgs",
      "repos_url": "https://api.github.com/users/robsonamendonca/repos",
      "events_url": "https://api.github.com/users/robsonamendonca/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonamendonca/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Robson-Rocha",
      "id": 12599932,
      "node_id": "MDQ6VXNlcjEyNTk5OTMy",
      "avatar_url": "https://avatars3.githubusercontent.com/u/12599932?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Robson-Rocha",
      "html_url": "https://github.com/Robson-Rocha",
      "followers_url": "https://api.github.com/users/Robson-Rocha/followers",
      "following_url": "https://api.github.com/users/Robson-Rocha/following{/other_user}",
      "gists_url": "https://api.github.com/users/Robson-Rocha/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Robson-Rocha/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Robson-Rocha/subscriptions",
      "organizations_url": "https://api.github.com/users/Robson-Rocha/orgs",
      "repos_url": "https://api.github.com/users/Robson-Rocha/repos",
      "events_url": "https://api.github.com/users/Robson-Rocha/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Robson-Rocha/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonkades",
      "id": 12546239,
      "node_id": "MDQ6VXNlcjEyNTQ2MjM5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/12546239?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonkades",
      "html_url": "https://github.com/robsonkades",
      "followers_url": "https://api.github.com/users/robsonkades/followers",
      "following_url": "https://api.github.com/users/robsonkades/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonkades/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonkades/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonkades/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonkades/orgs",
      "repos_url": "https://api.github.com/users/robsonkades/repos",
      "events_url": "https://api.github.com/users/robsonkades/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonkades/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robson-alecio",
      "id": 105332,
      "node_id": "MDQ6VXNlcjEwNTMzMg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/105332?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robson-alecio",
      "html_url": "https://github.com/robson-alecio",
      "followers_url": "https://api.github.com/users/robson-alecio/followers",
      "following_url": "https://api.github.com/users/robson-alecio/following{/other_user}",
      "gists_url": "https://api.github.com/users/robson-alecio/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robson-alecio/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robson-alecio/subscriptions",
      "organizations_url": "https://api.github.com/users/robson-alecio/orgs",
      "repos_url": "https://api.github.com/users/robson-alecio/repos",
      "events_url": "https://api.github.com/users/robson-alecio/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robson-alecio/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsoncastilho",
      "id": 1232263,
      "node_id": "MDQ6VXNlcjEyMzIyNjM=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1232263?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsoncastilho",
      "html_url": "https://github.com/robsoncastilho",
      "followers_url": "https://api.github.com/users/robsoncastilho/followers",
      "following_url": "https://api.github.com/users/robsoncastilho/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsoncastilho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsoncastilho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsoncastilho/subscriptions",
      "organizations_url": "https://api.github.com/users/robsoncastilho/orgs",
      "repos_url": "https://api.github.com/users/robsoncastilho/repos",
      "events_url": "https://api.github.com/users/robsoncastilho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsoncastilho/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsongajunior",
      "id": 3317013,
      "node_id": "MDQ6VXNlcjMzMTcwMTM=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3317013?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsongajunior",
      "html_url": "https://github.com/robsongajunior",
      "followers_url": "https://api.github.com/users/robsongajunior/followers",
      "following_url": "https://api.github.com/users/robsongajunior/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsongajunior/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsongajunior/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsongajunior/subscriptions",
      "organizations_url": "https://api.github.com/users/robsongajunior/orgs",
      "repos_url": "https://api.github.com/users/robsongajunior/repos",
      "events_url": "https://api.github.com/users/robsongajunior/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsongajunior/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Robsonsjre",
      "id": 11945073,
      "node_id": "MDQ6VXNlcjExOTQ1MDcz",
      "avatar_url": "https://avatars1.githubusercontent.com/u/11945073?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Robsonsjre",
      "html_url": "https://github.com/Robsonsjre",
      "followers_url": "https://api.github.com/users/Robsonsjre/followers",
      "following_url": "https://api.github.com/users/Robsonsjre/following{/other_user}",
      "gists_url": "https://api.github.com/users/Robsonsjre/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Robsonsjre/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Robsonsjre/subscriptions",
      "organizations_url": "https://api.github.com/users/Robsonsjre/orgs",
      "repos_url": "https://api.github.com/users/Robsonsjre/repos",
      "events_url": "https://api.github.com/users/Robsonsjre/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Robsonsjre/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonoduarte",
      "id": 797845,
      "node_id": "MDQ6VXNlcjc5Nzg0NQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/797845?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonoduarte",
      "html_url": "https://github.com/robsonoduarte",
      "followers_url": "https://api.github.com/users/robsonoduarte/followers",
      "following_url": "https://api.github.com/users/robsonoduarte/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonoduarte/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonoduarte/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonoduarte/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonoduarte/orgs",
      "repos_url": "https://api.github.com/users/robsonoduarte/repos",
      "events_url": "https://api.github.com/users/robsonoduarte/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonoduarte/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonagapito",
      "id": 991015,
      "node_id": "MDQ6VXNlcjk5MTAxNQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/991015?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonagapito",
      "html_url": "https://github.com/robsonagapito",
      "followers_url": "https://api.github.com/users/robsonagapito/followers",
      "following_url": "https://api.github.com/users/robsonagapito/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonagapito/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonagapito/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonagapito/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonagapito/orgs",
      "repos_url": "https://api.github.com/users/robsonagapito/repos",
      "events_url": "https://api.github.com/users/robsonagapito/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonagapito/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "vaamonde",
      "id": 21218780,
      "node_id": "MDQ6VXNlcjIxMjE4Nzgw",
      "avatar_url": "https://avatars3.githubusercontent.com/u/21218780?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vaamonde",
      "html_url": "https://github.com/vaamonde",
      "followers_url": "https://api.github.com/users/vaamonde/followers",
      "following_url": "https://api.github.com/users/vaamonde/following{/other_user}",
      "gists_url": "https://api.github.com/users/vaamonde/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vaamonde/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vaamonde/subscriptions",
      "organizations_url": "https://api.github.com/users/vaamonde/orgs",
      "repos_url": "https://api.github.com/users/vaamonde/repos",
      "events_url": "https://api.github.com/users/vaamonde/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vaamonde/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "sturobson",
      "id": 925197,
      "node_id": "MDQ6VXNlcjkyNTE5Nw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/925197?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sturobson",
      "html_url": "https://github.com/sturobson",
      "followers_url": "https://api.github.com/users/sturobson/followers",
      "following_url": "https://api.github.com/users/sturobson/following{/other_user}",
      "gists_url": "https://api.github.com/users/sturobson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sturobson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sturobson/subscriptions",
      "organizations_url": "https://api.github.com/users/sturobson/orgs",
      "repos_url": "https://api.github.com/users/sturobson/repos",
      "events_url": "https://api.github.com/users/sturobson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sturobson/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jdlrobson",
      "id": 148752,
      "node_id": "MDQ6VXNlcjE0ODc1Mg==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/148752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jdlrobson",
      "html_url": "https://github.com/jdlrobson",
      "followers_url": "https://api.github.com/users/jdlrobson/followers",
      "following_url": "https://api.github.com/users/jdlrobson/following{/other_user}",
      "gists_url": "https://api.github.com/users/jdlrobson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jdlrobson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jdlrobson/subscriptions",
      "organizations_url": "https://api.github.com/users/jdlrobson/orgs",
      "repos_url": "https://api.github.com/users/jdlrobson/repos",
      "events_url": "https://api.github.com/users/jdlrobson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jdlrobson/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "roppa",
      "id": 98824,
      "node_id": "MDQ6VXNlcjk4ODI0",
      "avatar_url": "https://avatars0.githubusercontent.com/u/98824?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/roppa",
      "html_url": "https://github.com/roppa",
      "followers_url": "https://api.github.com/users/roppa/followers",
      "following_url": "https://api.github.com/users/roppa/following{/other_user}",
      "gists_url": "https://api.github.com/users/roppa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/roppa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/roppa/subscriptions",
      "organizations_url": "https://api.github.com/users/roppa/orgs",
      "repos_url": "https://api.github.com/users/roppa/repos",
      "events_url": "https://api.github.com/users/roppa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/roppa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonrosa",
      "id": 2868031,
      "node_id": "MDQ6VXNlcjI4NjgwMzE=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/2868031?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonrosa",
      "html_url": "https://github.com/robsonrosa",
      "followers_url": "https://api.github.com/users/robsonrosa/followers",
      "following_url": "https://api.github.com/users/robsonrosa/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonrosa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonrosa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonrosa/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonrosa/orgs",
      "repos_url": "https://api.github.com/users/robsonrosa/repos",
      "events_url": "https://api.github.com/users/robsonrosa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonrosa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "robsonperassoli",
      "id": 625089,
      "node_id": "MDQ6VXNlcjYyNTA4OQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/625089?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robsonperassoli",
      "html_url": "https://github.com/robsonperassoli",
      "followers_url": "https://api.github.com/users/robsonperassoli/followers",
      "following_url": "https://api.github.com/users/robsonperassoli/following{/other_user}",
      "gists_url": "https://api.github.com/users/robsonperassoli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robsonperassoli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robsonperassoli/subscriptions",
      "organizations_url": "https://api.github.com/users/robsonperassoli/orgs",
      "repos_url": "https://api.github.com/users/robsonperassoli/repos",
      "events_url": "https://api.github.com/users/robsonperassoli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robsonperassoli/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "arobson",
      "id": 115508,
      "node_id": "MDQ6VXNlcjExNTUwOA==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/115508?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/arobson",
      "html_url": "https://github.com/arobson",
      "followers_url": "https://api.github.com/users/arobson/followers",
      "following_url": "https://api.github.com/users/arobson/following{/other_user}",
      "gists_url": "https://api.github.com/users/arobson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/arobson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/arobson/subscriptions",
      "organizations_url": "https://api.github.com/users/arobson/orgs",
      "repos_url": "https://api.github.com/users/arobson/repos",
      "events_url": "https://api.github.com/users/arobson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/arobson/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
''';
